=== Dixya60/Web_Tech/XML/Lab-3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="book">
                    <xs:complexType>

                        <xs:sequence>

                            <xs:element name="name" type="xs:string"/>

                            <xs:element name="author" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" type="xs:string"/>
                                        <xs:element name="middlename" type="xs:string"/>
                                        <xs:element name="lastname" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="pageno" type="xs:integer"/>

                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:maxInclusive value="1000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="isbn" type="xs:string" use="required"/>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Dixya60/Web_Tech/XML/Lab-3.xml
<?xml version="1.0" encoding="UTF-8"?>

<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Lab-3.xsd">

    <book isbn="ISBN-001">

        <name>Database Management System</name>

        <author>
            <firstname>Abraham</firstname>
            <middlename>J.</middlename>
            <lastname>Silberschatz</lastname>
        </author>

        <author>
            <firstname>Henry</firstname>
            <middlename>F.</middlename>
            <lastname>Korth</lastname>
        </author>

        <pageno>650</pageno>
        <price>900</price>

    </book>
</books>
